### ISSUE TITLE
Rd semantics

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#114]
The preference of the authors and most implementors so far is:

    leaf rd {
      type union {
      type rt-types:route-distinguisher;
       type empty;
    }
}
The alternative proposal is:
    leaf rd {
      type rt-types:route-distinguisher;
    }

    leaf auto-assign-rd {
      when "not(../rd)";
      type boolean;
    }

Check with our Yang doctor

**Comment by billwuqin** [comment]
I think Roque's proposal has been changed into:
    leaf rd {
      type rt-types:route-distinguisher;
    }
    container dynamic-assign-rd {
      presence "Auto-assign-rd";
      when "not(../rd)";
      leaf rd-pool-name {
        type string;
      }
    }
Even with this change, I still think it adds complexity.
1. the upper layer oss should not care about which RD is allocated from which RD pool if the upper layer oss delegates RD assignment task to the controller, the upper layer oss should completely trust controller to do a good job.
2. which RD is from which RD pool, this is more related to service maintenance, it should be put into separate module.
My 2 cents.

Orignal proposal has bug, since if RD is not assigned by upper layer oss, the auto-assign-rd is always true, if RD is assigned by upper layer oss, the auto-assign-rd should be always false.
I am not sure it is necessary to consult with YANG doctor for this.

**Comment by rgaglian** [comment]
BTW, an better alternative would be to use the CASE statement. I can work on a proposal.

**Comment by rgaglian** [comment]
Here is an option using choice/case that can faciliate the work for implementations/troubleshooting:  

  choice rd-choice {
      case directly-assigned {
        leaf rd {
          type rt-types:route-distinguisher;
        }
      }
      case pool-assigned {
        leaf rd-pool-name {
          type string;
        }
      }
      case no-rd {
        leaf no-rd {
          type empty;
        }
      }
    }

**Comment by billwuqin** [comment]
Proposed change sounds good to me.

**Comment by sbarguil** [comment]
4bf6abcfc958c0f96551bc1c944e82bcf1818626

Done available in https://github.com/IETF-OPSAWG-WG/l3nm/pull/172

**Comment by oscargdd** [comment]
Samier has sent pull request #172
