### ISSUE TITLE
RT / RD autoasigment by controller Flag

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#20]
We need to indicate wether the RT and RDs are provided by the Network Operator / service orchestrator or they are automatically asigned by the controller which has the l3nm module

**Comment by sli35** [comment]
As discussed offline, this discussion goes beyond RD/RTs and may be applicable to other parameters like VLANs,...
In addition RD and RTs may be computed rather than allocated. For example RD may be computed from an allocated VPN-ID plus some RTR_ID while RTs may be computed from VPN-ID and vpn-type.

**Comment by sunseawq** [comment]
That's why VLAN, interface-id are optional parameters in L3NM model, so does RD. I think it has no harm to keep them since we need to accommodate various different implementation choices, e.g, multiple domain under the same administrative domain. If they are not filled, it can be computed by controller using  VPN-ID and other information.

**Comment by oscargdd** [comment]
The behavior that non-mandatory parameters and are config true are expanded by the server which hosts the yang module (either by a template or whatever mechanism is used) is perfectly compliant with NMDA architecture. 
There is a needed behavior which is currently not supported: We need to be able to explicitly indicate the no RT/RD are wanted. For that, we could use a choice between a value and a NONE.

**Comment by sunseawq** [comment]
I think the proposal you offered in opsawg session is perfectly fine since it only focus on who provide RD, RT rather than how RD RT is allocated or provided or computed or derived. With this proposal, it does cover all the cases. But if explicitly indicate RD or RT is needed, we may have face, in some case, RT is needed, in some cases RD is needed, in some case both RT and RD are needed, in some case both RT and RD are not needed. So I perfer your original proposal to address this issue.

**Comment by oscargdd** [comment]
Martin suggestion in netmod mailing list question:
For your "auto-assignment" case, I would describe the behaviour in the description statement.  Something like: "If this leaf has not been configured, the server will calculate a value [... specify how ... ] and use that value operationally.  This calculated value is available in the operational state."

**Comment by oscargdd** [comment]
Agreement on the Group:
1) Follow Martin's suggestion and add the description in the leaft
2) Add a clarification section in the draft (section  6.3.3)

**Comment by billwuqin** [comment]
Here is the example of empty leaf in RFC7950, is this what you are looking for?
9.11.4.  Usage Example


   With the following leaf:

     leaf enable-qos {
       type empty;
     }

   the following is an example of a valid encoding if the leaf exists:

     <enable-qos/>

**Comment by oscargdd** [comment]
Implemented in 3b74db5a029d44e1c51a87c61c9e7a67696fc392 with Qin's proposal:

 grouping rt-rd {
    leaf rd {
      type union {
	    type rt-types:route-distinguisher;
	    type empty;
	  }
      description
        "Route distinguisher value. If this leaf has not been configured, the server will auto-assign a route distinguisher value and use that 
		value operationally. This calculated value is available in the operational state. Use the
		empty type to indicate rd has no value and
		is not to be aouto-assigned";
    }

**Comment by oscargdd** [comment]
Now, only the explanatory text in the draft is needed

**Comment by oscargdd** [comment]
we close this one and maintain issue #114
