### ISSUE TITLE
[proposed labels: L2NM, L3NM] Add useful fields from CSMs to NSMs

### ISSUE THREAD

**Issue by kireeti1** [IETF-OPSAWG-WG/l3nm#209]
RFC 8466/8299 have “site-id”, “device-id” and “location-id” fields that have significance to the customer, but not to the operator.  So, understandably, the NSM (draft-ietf-opsawg-l[23]s-l[23]nm) skips these fields.  However, these may be useful in communicating to the customer about maintenance or an outage; in general, in troubleshooting.  If they are carried over to the NSM, they can go into description fields in the PE devices implementing the service for easy access by NOC personnel.

Furthermore, there is a single address field for the device (CE).  It may be useful to have both the loopback of the device as well as the interface address.  Of course, that would require an update to the CSMs, so this might be a bigger change.

**Comment by oscargdd** [comment]
The model already supports multiple addresses.

**Comment by boucadair** [comment]
> 
> 
> RFC 8466/8299 have “site-id”, “device-id” and “location-id” fields that have significance to the customer, but not to the operator. So, understandably, the NSM (draft-ietf-opsawg-l[23]s-l[23]nm) skips these fields. However, these may be useful in communicating to the customer about maintenance or an outage; in general, in troubleshooting. If they are carried over to the NSM, they can go into description fields in the PE devices implementing the service for easy access by NOC personnel.
> 

We do have a pointer to the L3SM which contains these infromation. 

If an L3SM is not present, the information can be provided locally in the controller which can mainatin a mapping with these IDs. 

Not sure I see a value in exposing these in the L3NM.

**Comment by sbarguil** [comment]
At service level we have the hook to map the L3SM (information) and the L3NM:
```
     +--rw vpn-services
        +--rw vpn-service* [vpn-id]
           +--rw vpn-id                   vpn-id
           +--rw vpn-name?                string
           +--rw vpn-description?         string
           +--rw customer-name?           string
           +--rw l3sm-vpn-id?             vpn-common:vpn-id
```

If several customers are in the same VPN (i.e. Mixed VPN) this information can not be mapped. 

One feasible solution is to include the l3snm-sna-id and l3sm-vpnode-id at Vpn-Network-Access and VPN-Node level respectivley.

**Comment by julianL999** [comment]
Having the site-id information in the L3NM/L2NM is important because it indicates whether or not a site is multi-homed, which affects the configuration required on the router. For example, in the L3VPN case if we know from the L3NM that a site is homed to PE1 and PE2, and BGP is the PE-CE protocol, we know that we should set a BGP site-of-origin community to prevent routing-loops. Similarly, in the EVPN case, we need to set the same ESI on the two PE-CE links. It would be better to have that information contained in the NM, rather than having to look at the SM as well. (Furthermore, in Figure 1 of the L3NM draft, the Network Orchestrator only "sees" the NM and not the SM). Site-id is at the /l3vpn-svc/sites/site/site-id level in the L3SM  - as mentioned in previous comment it would be good to add it to vpn-network-access in the NM. (Device-id and location-id would be useful to put in NM as well, as they are usually used in description fields in the PE config)

**Comment by boucadair** [comment]
> Site-id is at the /l3vpn-svc/sites/site/site-id level in the L3SM - as mentioned in previous comment it would be good to add it to vpn-network-access in the NM. (Device-id and location-id would be useful to put in NM as well, as they are usually used in description fields in the PE config)

Julian, for this part, this is really up to the implementation and if you need to use of these service nodes in the interface desc

> For example, in the L3VPN case if we know from the L3NM that a site is homed to PE1 and PE2, and BGP is the PE-CE protocol, we know that we should set a BGP site-of-origin community to prevent routing-loops.

Thanks, Julian. This is a good one to capture in the model. A proposal is to add a node to control SOO at the BGP node level. 

I would prefer that path compared to inheriting more "service-related" information that we are not sure will impact the network configuration.

**Comment by julianL999** [comment]
> 
> > For example, in the L3VPN case if we know from the L3NM that a site is homed to PE1 and PE2, and BGP is the PE-CE protocol, we know that we should set a BGP site-of-origin community to prevent routing-loops.
> 
> Thanks, Julian. This is a good one to capture in the model. A proposal is to add a node to control SOO at the BGP node level.
> 
> I would prefer that path compared to inheriting more "service-related" information that we are not sure will impact the network configuration. Thanks.

OK, thanks, that would the job. We would also need something in the L2NM for multi-homed L2-services (e.g. to trigger setting EVPN ESI in the config accordingly)

**Comment by boucadair** [comment]
> OK, thanks Med, that would do the job.

Fixed at https://github.com/IETF-OPSAWG-WG/l3nm/commit/52e871b1b30d6685b51b40fc10a4709df18958ea

> We would also need to think about something in the L2NM for multi-homed L2-services (e.g. to trigger setting EVPN ESI in the config accordingly)

We need to open a separate issue to track this one. Thanks.

**Comment by julianL999** [comment]
Actually Med, shouldn't the fix have a place for the SoO community value (rather than a boolean)? Because BGP sessions that go to the same site need to add the same value on import.

**Comment by julianL999** [comment]
It has just occurred to me that in the VRRP case, it is important to know which site is multihomed to which PEs, so the PEs can be configured accordingly (e.g. setting the same Virtual IP address on the PEs)

**Comment by boucadair** [comment]
> 
> 
> Actually Med, shouldn't the fix have a place for the SoO community value (rather than a boolean)? Because BGP sessions that go to the same site need to add the same value on import.

Hi Julian, 

You are right. Please see https://github.com/IETF-OPSAWG-WG/l3nm/commit/7a4b3d1eddcf70768a9e29f70c7a16db8bf16fa2; this covers both IPv4 and IPv6. 

Hope this is better.

**Comment by boucadair** [comment]
Hi Julian,

For me, that’s an internal process that happens when translating the service request into L3NM. No?

Thanks.

De : julianL999 [mailto:notifications@github.com]

It has just occurred to me that in the VRRP case, it is important to know which site is multihomed to which PEs, so the PEs can be configured accordingly (e.g. setting the same Virtual IP address on the PEs)

_________________________________________________________________________________________________________________________

Ce message et ses pieces jointes peuvent contenir des informations confidentielles ou privilegiees et ne doivent donc
pas etre diffuses, exploites ou copies sans autorisation. Si vous avez recu ce message par erreur, veuillez le signaler
a l'expediteur et le detruire ainsi que les pieces jointes. Les messages electroniques etant susceptibles d'alteration,
Orange decline toute responsabilite si ce message a ete altere, deforme ou falsifie. Merci.

This message and its attachments may contain confidential or privileged information that may be protected by law;
they should not be distributed, used or copied without authorisation.
If you have received this email in error, please notify the sender and delete this message and its attachments.
As emails may be altered, Orange is not liable for messages that have been modified, changed or falsified.
Thank you.

**Comment by julianL999** [comment]
> Hi Julian, For me, that’s an internal process that happens when translating the service request into L3NM. No? Thanks. De : julianL999 [mailto:notifications@github.com] It has just occurred to me that in the VRRP case, it is important to know which site is multihomed to which PEs, so the PEs can be configured accordingly (e.g. setting the same Virtual IP address on the PEs)

Actually I just realised the Virtual IP address can go into the "/l3vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/vpn-network-accesses/vpn-network-access/routing-protocols/routing-protocol/vrrp/backup-peer" field. (As there is no need to specify the backup-peer, so we can use this field for the Virtual IP address instead).
