### ISSUE TITLE
BGP Sesion Parameters

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#35]
We have detected are missing in the L3NM in order to fully accomplish the configuration of the BGP session in our operations. Some of these parameters are really device-specific so We would like to hear your opinion in order to determine how to handle it; Should we included in our network model?

The parameters are:

- AS Override
- Generate Default-Route
- Threshold Interval and Hold Timer of the BGP Session
- Peer Group Creation
- In/Out Route-Maps

**Comment by segevere** [comment]
1. AS-Override - we can add to container local-as in addition to peer-as per session 
2. Generate -default -route   - peer group level of configuration and per afi-safi
3, Threshold Interval and Hold Timer of the BGP Session -can be solved by having BGP profile 
4. Peer Group Creation - depend on amount of neighbors and granularity , BGP standard requires it , but I believe its parameters can be pushed to Neighbor configuration 
5. In/Out Route-Maps - is it the policy? can be reference to policy name , adding a policy profile statement to vpn-profiles.
in addition :
6.  in my equipment model (based on standard) , the BGP setting is on the VRF and for IPv6 link-local operator must indicate the outgoing interface.
7. BFD - controller can activate BFD in PE-CE protocol (for dual homing)
8. enabled /disabled - shall be added as well

**Comment by sbarguil** [comment]
Adding just a few comments. 

1. AS-Override - Local AS exits in the model. However, this override must remove the Peer-AS and just propagate the SP-AS. In this case, there is no way to express this behavior. 

5.In/Out Route-Maps - is it the policy, but our users were expecting to be able to create the policy it self. Not just reference it. 

BFD - Agree 
Status. enabled /disabled - Agree

**Comment by segevere** [comment]
1.  AS-Override - isnt it "replace-peer-as" as describe in https://tools.ietf.org/html/draft-ietf-idr-bgp-model-07
5. policy may be controlled regardless the BGP  as in-depended entity.

**Comment by sbarguil** [comment]
1. AS-Override: Yes
2. It can be a good approach. Can we put the reference in the `routing-profiles* [id] `

**Comment by boucadair** [comment]
I see a value in having "In/Out Route-Maps" to the module (assuming there is an interface to feed this from the customers). 

For the other parameters, I think this up to the device model to handle this. We might consider BGP profiles and communicate a pointer when it comes to enforcing the config at the device level.

**Comment by billwuqin** [comment]
I see the value for BGP timer, we could add keep-alive and hold-time for BGP timer.
For BFD, I think we have already defined OAM/BFD under IP-connection, I am wondering whether BFD parameter is specific to BGP, does it apply to static-route as well? In addition, do we need to add echo-disable, is it device specifc or not?

**Comment by billwuqin** [comment]
In addition, 
1.do we need to maintain the mapping between network prefix and RT or set community, do we need to link this mapping to route-policy?
2.Do we need to support route aggregation, similar to mapping between network prefix and set community?

**Comment by billwuqin** [comment]
Do we need to distinguish IPv4 RT from IPv6 RT?

**Comment by segevere** [comment]
> Do we need to distinguish IPv4 RT from IPv6 RT?

I believe RT is assigned regardless the IP version  how ever you can control what is forward via export policy
 

>do we need to maintain the mapping between network prefix and RT or set community, do we need to link this mapping to route-policy?

can you add an example?


> 2.Do we need to support route aggregation, similar to mapping between network prefix and set community?

Route aggregation is needed , not familiar with details 


> I see the value for BGP timer, we could add keep-alive and hold-time for BGP timer.
> For BFD, I think we have already defined OAM/BFD under IP-connection, I am wondering whether BFD parameter is specific to BGP, does it apply to static-route as well? In addition, do we need to add echo-disable, is it device specifc or not?

yes, BFD should be part of static routes and BGP as well, I never understand the bfd under IP connection since it should be per peer.

**Comment by billwuqin** [comment]
Do we need to distinguish IPv4 RT from IPv6 RT?

I believe RT is assigned regardless the IP version how ever you can control what is forward via export policy
[Qin]: So address family should be part of export policy or in other words, one new  parameter address family should be added?
do we need to maintain the mapping between network prefix and RT or set community, do we need to link this mapping to route-policy?

can you add an example?
[Qin]:Something like this:
    +--rw networks
    |  +--rw networks-entry* [network-prefixs]
    |     +--rw network-prefixs    inet:ipv4-prefix
    |     +--rw route-policy
    |        +--rw policy-name?     string
    |        +--rw route-target?   rt-types:route-target
2.Do we need to support route aggregation, similar to mapping between network prefix and set community?

Route aggregation is needed , not familiar with details
[Qin]: Something like this:
    +--rw routing-aggregations
       +--rw routing-aggregation* [network mask]
          +--rw network         inet:ipv4-address
          +--rw mask            uint8
          +--rw summary-only?   boolean
          +--rw as-set?         boolean

I see the value for BGP timer, we could add keep-alive and hold-time for BGP timer.
For BFD, I think we have already defined OAM/BFD under IP-connection, I am wondering whether BFD parameter is specific to BGP, does it apply to static-route as well? In addition, do we need to add echo-disable, is it device specifc or not?

yes, BFD should be part of static routes and BGP as well, I never understand the bfd under IP connection since it should be per peer.
[Qin]:bfd under IP connection means it is per vpn-network-access or per port.

**Comment by billwuqin** [comment]
The proposal is:
        container bgp-timer {
            leaf keep-alive {
                type uint16;
                default 60;
                units "seconds";
            }
            leaf hold-time {
                type uint16;
                default 180;
                units "seconds";
            }
        }
